<?php 
if ( ! defined( 'WPINC' ) ) {
    die;
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Event Plugun</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<style>
    body {
        font-family: 'Roboto', sans-serif;
    }
    
    .text-center {
        text-align: center;
    }
    
    .wrap {
        margin-bottom: 20px;
    }
    
    .blue-box {
        background: #3F51B5;
        color: #fff;
        border-top-right-radius: 0px;
        border-top-left-radius: 0px;
        padding: 1px;
        font-size: 20px;
    }
    
    .info {
        border: 1px solid #ddd;
        padding: 6px;
    }
    
    .blue-box p {
        margin-top: 12px;
        margin-bottom: 10px;
        letter-spacing: 1px;
    }
    
    .blue-box strong {
        letter-spacing: 1.5px;
    }
    
    .mfooter {
        border: 1px solid #ddd;
        background: #3f51b5;
        padding: 7px 15px 28px;
        color: #fff;
    }
    
    .mfooter a {
        color: #ddd;
    }
</style>

<body style="margin: 0; padding: 0; font-family: 'Roboto', sans-serif;">
    <table align="center" cellpadding="0" cellspacing="0" width="600" style="margin-top: 60px;">
        <tr>
            <td align="center" style="padding: 40px 0px 15px 0px;">
                <div class="wrap">
                    <div class="blue-box text-center" style="background: #3F51B5; color: #fff; border-top-right-radius: 0px; border-top-left-radius: 0px; padding: 1px; font-size: 20px;">
                        <?php echo $this->subject ?>
                    </div>
                    <img src="<?php echo get_option("event_plugun_template_logo") ?>" alt="" width="" height="" style="display: block;" />
                    <div class="info">

                
                <?php 
    
        if(isset($template)){
            require_once(__DIR__ . "/" . $template);
        } 
        else if($message) {
            echo $message;  
        }
    
     ?>

              </div>
            
         </div>       
                </td>
            </tr>
             <tr>
                <td>    
                    
                    <?php echo get_option("event_plugun_template_footer") ?>
              </td>
        </tr>
    </table>

</body>

</html>